/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DaoEmail;
import dao.DaoPetugas;
import dao.Encrypt;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import parsisten.Petugas;
import servis.ServiceEmail;
import servis.ServicePetugas;

/**
 *
 * @author fatiq
 */
public class LupaPassword extends javax.swing.JDialog {

    /**
     * Creates new form LupaPassword
     */
    private Petugas mod = null;
    private String kode = "";
    private ServicePetugas servis = new DaoPetugas();
    private ServiceEmail serv = new DaoEmail();

    public LupaPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        pn_main.removeAll();
        pn_main.repaint();
        pn_main.revalidate();

        pn_main.add(step1);
        pn_main.repaint();
        pn_main.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCustom1 = new custom.JPanelCustom();
        jPanelCustom2 = new custom.JPanelCustom();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();
        step1 = new javax.swing.JPanel();
        tf_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_next1 = new javax.swing.JButton();
        step2 = new javax.swing.JPanel();
        tf_kode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_next2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        btn_kirim = new javax.swing.JButton();
        step3 = new javax.swing.JPanel();
        btn_next3 = new javax.swing.JButton();
        tf_pass1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        unhide1 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        unhide2 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanelCustom1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelCustom1.setKananAtas(30);
        jPanelCustom1.setKananBawah(30);
        jPanelCustom1.setKiriAtas(30);
        jPanelCustom1.setKiriBawah(30);

        jPanelCustom2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCustom2.setKananAtas(30);
        jPanelCustom2.setKananBawah(30);
        jPanelCustom2.setKiriAtas(30);
        jPanelCustom2.setKiriBawah(30);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lupa Password");

        pn_main.setLayout(new java.awt.CardLayout());

        step1.setBackground(new java.awt.Color(255, 255, 255));

        tf_email.setForeground(new java.awt.Color(68, 50, 124));
        tf_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 50, 124));
        jLabel7.setText("Email");

        tf_username.setForeground(new java.awt.Color(68, 50, 124));
        tf_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 50, 124));
        jLabel10.setText("Username");

        btn_next1.setBackground(new java.awt.Color(0, 0, 200));
        btn_next1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_next1.setForeground(new java.awt.Color(255, 255, 255));
        btn_next1.setText("NEXT");
        btn_next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout step1Layout = new javax.swing.GroupLayout(step1);
        step1.setLayout(step1Layout);
        step1Layout.setHorizontalGroup(
            step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_username)
                    .addGroup(step1Layout.createSequentialGroup()
                        .addGroup(step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_email)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step1Layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(btn_next1)))
                .addContainerGap())
        );
        step1Layout.setVerticalGroup(
            step1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_next1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_main.add(step1, "card2");

        step2.setBackground(new java.awt.Color(255, 255, 255));

        tf_kode.setForeground(new java.awt.Color(68, 50, 124));
        tf_kode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 50, 124));
        jLabel8.setText("Kode");

        btn_next2.setBackground(new java.awt.Color(0, 0, 200));
        btn_next2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_next2.setForeground(new java.awt.Color(255, 255, 255));
        btn_next2.setText("VERIFIKASI");
        btn_next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kami telah mengrim kode ke email");

        lb_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_email.setForeground(new java.awt.Color(0, 0, 0));
        lb_email.setText("email");

        btn_kirim.setBackground(new java.awt.Color(0, 200, 0));
        btn_kirim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_kirim.setForeground(new java.awt.Color(255, 255, 255));
        btn_kirim.setText("Kirim ulang kode");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout step2Layout = new javax.swing.GroupLayout(step2);
        step2.setLayout(step2Layout);
        step2Layout.setHorizontalGroup(
            step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_kode)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step2Layout.createSequentialGroup()
                        .addComponent(btn_kirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next2))
                    .addGroup(step2Layout.createSequentialGroup()
                        .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        step2Layout.setVerticalGroup(
            step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(lb_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(step2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kirim)
                    .addComponent(btn_next2))
                .addContainerGap())
        );

        pn_main.add(step2, "card2");

        step3.setBackground(new java.awt.Color(255, 255, 255));

        btn_next3.setBackground(new java.awt.Color(0, 0, 200));
        btn_next3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_next3.setForeground(new java.awt.Color(255, 255, 255));
        btn_next3.setText("UBAH PASWWORD");
        btn_next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next3ActionPerformed(evt);
            }
        });

        tf_pass1.setForeground(new java.awt.Color(68, 50, 124));
        tf_pass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        tf_pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_pass1MouseExited(evt);
            }
        });
        tf_pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pass1KeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unhide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unhide.png"))); // NOI18N
        unhide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unhide1MouseClicked(evt);
            }
        });
        jPanel2.add(unhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        jPanel2.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 50, 124));
        jLabel12.setText("Ulangi Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        tf_pass.setForeground(new java.awt.Color(68, 50, 124));
        tf_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 50, 124));
        jLabel11.setText("Password");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unhide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unhide.png"))); // NOI18N
        unhide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unhide2MouseClicked(evt);
            }
        });
        jPanel3.add(unhide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide2MouseClicked(evt);
            }
        });
        jPanel3.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout step3Layout = new javax.swing.GroupLayout(step3);
        step3.setLayout(step3Layout);
        step3Layout.setHorizontalGroup(
            step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(step3Layout.createSequentialGroup()
                        .addGap(0, 127, Short.MAX_VALUE)
                        .addComponent(btn_next3))
                    .addComponent(tf_pass1)
                    .addComponent(tf_pass)
                    .addGroup(step3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(step3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        step3Layout.setVerticalGroup(
            step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(step3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(tf_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_next3)
                .addContainerGap())
        );

        pn_main.add(step3, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustom2Layout.createSequentialGroup()
                        .addGroup(jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustom2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCustom1Layout = new javax.swing.GroupLayout(jPanelCustom1);
        jPanelCustom1.setLayout(jPanelCustom1Layout);
        jPanelCustom1Layout.setHorizontalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustom1Layout.setVerticalGroup(
            jPanelCustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next1ActionPerformed
        String user = tf_username.getText();
        String email = tf_email.getText();

        List<Petugas> list = servis.ambilData();
        for (Petugas p : list) {
            if (user.equals(p.getUsername()) && email.equals(p.getEmail())) {
                this.mod = p;
            }
        }

        if (mod == null) {
            JOptionPane.showMessageDialog(null, "Tidak ada kombinasi username dan email yang sama");
        } else {
            lb_email.setText(mod.getEmail());
            this.kode = serv.krirmKode(mod.getEmail());

            pn_main.removeAll();
            pn_main.repaint();
            pn_main.revalidate();

            pn_main.add(step2);
            pn_main.repaint();
            pn_main.revalidate();
        }
    }//GEN-LAST:event_btn_next1ActionPerformed

    private void btn_next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next2ActionPerformed
        String k = tf_kode.getText();
        if(this.kode.equals(k)){
            pn_main.removeAll();
            pn_main.repaint();
            pn_main.revalidate();

            pn_main.add(step3);
            pn_main.repaint();
            pn_main.revalidate();
        } else {
            JOptionPane.showMessageDialog(null, "Kode salah");
        }
    }//GEN-LAST:event_btn_next2ActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        this.kode = serv.krirmKode(mod.getEmail());
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void btn_next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next3ActionPerformed
        mod.setPassword(Encrypt.getmd5java(tf_pass.getText()));
        servis.ubahData(mod);
        dispose();
    }//GEN-LAST:event_btn_next3ActionPerformed

    private void tf_pass1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_pass1MouseExited
        String pass = tf_pass.getText();
        String pass1 = tf_pass1.getText();
        if (pass.equals("")) {
            jLabel4.setText("Passsord tidak boleh kosong");
            jLabel4.setForeground(new Color(200, 0, 0));
        } else if (pass.equals(pass1)) {
            jLabel4.setText("Passsord sama");
            jLabel4.setForeground(new Color(0, 200, 0));
        } else {
            jLabel4.setText("Passsord tidak sama");
            jLabel4.setForeground(new Color(200, 0, 0));
        }
    }//GEN-LAST:event_tf_pass1MouseExited

    private void tf_pass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pass1KeyTyped
        String pass = tf_pass.getText();
        String pass1 = tf_pass1.getText();
        if (pass.equals("")) {
            jLabel4.setText("Passsord tidak boleh kosong");
            jLabel4.setForeground(new Color(200, 0, 0));
        } else if (pass.equals(pass1)) {
            jLabel4.setText("Passsord sama");
            jLabel4.setForeground(new Color(0, 200, 0));
        } else {
            jLabel4.setText("Passsord tidak sama");
            jLabel4.setForeground(new Color(200, 0, 0));
        }
    }//GEN-LAST:event_tf_pass1KeyTyped

    private void unhide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhide1MouseClicked
        tf_pass.setEchoChar('*');
        hide1.setVisible(true);
        unhide1.setVisible(false);
    }//GEN-LAST:event_unhide1MouseClicked

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        tf_pass.setEchoChar((char) 0);
        hide1.setVisible(false);
        unhide1.setVisible(true);
    }//GEN-LAST:event_hide1MouseClicked

    private void unhide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhide2MouseClicked
        tf_pass1.setEchoChar('*');
        hide2.setVisible(true);
        unhide2.setVisible(false);
    }//GEN-LAST:event_unhide2MouseClicked

    private void hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseClicked
        tf_pass1.setEchoChar((char) 0);
        hide2.setVisible(false);
        unhide2.setVisible(true);
    }//GEN-LAST:event_hide2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LupaPassword dialog = new LupaPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_next1;
    private javax.swing.JButton btn_next2;
    private javax.swing.JButton btn_next3;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private custom.JPanelCustom jPanelCustom1;
    private custom.JPanelCustom jPanelCustom2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JPanel step3;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_kode;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JPasswordField tf_pass1;
    private javax.swing.JTextField tf_username;
    private javax.swing.JLabel unhide1;
    private javax.swing.JLabel unhide2;
    // End of variables declaration//GEN-END:variables
}
