/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import parsisten.Petugas;

/**
 *
 * @author fatiq
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public static boolean aktif = true;
    public static Petugas mod = new Petugas();
    private JPopupMenu popupMenu = new JPopupMenu();

    public MenuUtama(Petugas mod) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.mod = mod;
        pn_select1.setVisible(false);
        pn_select2.setVisible(false);
        pn_select5.setVisible(false);
        pn_select6.setVisible(false);
        pn_select8.setVisible(false);
        pn_select9.setVisible(false);
        pn_select10.setVisible(false);

        if (!mod.getLevel().equalsIgnoreCase("Admin")) {
            pn_btnPetugas.setVisible(false);
        }

        book1.removeAll();
        book1.add(new MenuDasbor(book1, jLabel4, jLabel6, jLabel14, jLabel8, jLabel2));
        book1.repaint();
        book1.revalidate();
        popupMenu.add(menu1);
        popupMenu.add(menu);
    }

    private MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenu();
        menu1 = new javax.swing.JMenu();
        pn_menuBar = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        pn_btnDasbor = new javax.swing.JPanel();
        pn_select1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_btnAnggota = new javax.swing.JPanel();
        pn_select2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_btnBuku = new javax.swing.JPanel();
        pn_select5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_btnPeminjaman = new javax.swing.JPanel();
        pn_select6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_btnLaporan = new javax.swing.JPanel();
        pn_select8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pn_btnSkripsi = new javax.swing.JPanel();
        pn_select9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn_btnPetugas = new javax.swing.JPanel();
        pn_select10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pn_dasbor = new javax.swing.JPanel();
        pn_heder = new custom.JPanelGradientHorizontal();
        btn_s = new javax.swing.JLabel();
        book1 = new javax.swing.JPanel();

        menu.setText("Logout");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        menu1.setText("Profil");
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LibraLinx");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/iconlibralinx.png")).getImage());

        pn_menuBar.setBackground(new java.awt.Color(255, 255, 255));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libralinx.png"))); // NOI18N

        pn_btnDasbor.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnDasbor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnDasborMouseMoved(evt);
            }
        });
        pn_btnDasbor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnDasborMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnDasborMouseExited(evt);
            }
        });

        pn_select1.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select1Layout = new javax.swing.GroupLayout(pn_select1);
        pn_select1.setLayout(pn_select1Layout);
        pn_select1Layout.setHorizontalGroup(
            pn_select1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select1Layout.setVerticalGroup(
            pn_select1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dasbor.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout pn_btnDasborLayout = new javax.swing.GroupLayout(pn_btnDasbor);
        pn_btnDasbor.setLayout(pn_btnDasborLayout);
        pn_btnDasborLayout.setHorizontalGroup(
            pn_btnDasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDasborLayout.createSequentialGroup()
                .addComponent(pn_select1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnDasborLayout.setVerticalGroup(
            pn_btnDasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnAnggota.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnAnggota.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseMoved(evt);
            }
        });
        pn_btnAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnAnggotaMouseExited(evt);
            }
        });

        pn_select2.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select2Layout = new javax.swing.GroupLayout(pn_select2);
        pn_select2.setLayout(pn_select2Layout);
        pn_select2Layout.setHorizontalGroup(
            pn_select2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select2Layout.setVerticalGroup(
            pn_select2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anggota.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Anggota");

        javax.swing.GroupLayout pn_btnAnggotaLayout = new javax.swing.GroupLayout(pn_btnAnggota);
        pn_btnAnggota.setLayout(pn_btnAnggotaLayout);
        pn_btnAnggotaLayout.setHorizontalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnAnggotaLayout.createSequentialGroup()
                .addComponent(pn_select2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnAnggotaLayout.setVerticalGroup(
            pn_btnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnBuku.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnBuku.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseMoved(evt);
            }
        });
        pn_btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnBukuMouseExited(evt);
            }
        });

        pn_select5.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select5Layout = new javax.swing.GroupLayout(pn_select5);
        pn_select5.setLayout(pn_select5Layout);
        pn_select5Layout.setHorizontalGroup(
            pn_select5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select5Layout.setVerticalGroup(
            pn_select5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Buku");

        javax.swing.GroupLayout pn_btnBukuLayout = new javax.swing.GroupLayout(pn_btnBuku);
        pn_btnBuku.setLayout(pn_btnBukuLayout);
        pn_btnBukuLayout.setHorizontalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnBukuLayout.createSequentialGroup()
                .addComponent(pn_select5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnBukuLayout.setVerticalGroup(
            pn_btnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnPeminjaman.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnPeminjaman.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseMoved(evt);
            }
        });
        pn_btnPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPeminjamanMouseExited(evt);
            }
        });

        pn_select6.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select6Layout = new javax.swing.GroupLayout(pn_select6);
        pn_select6.setLayout(pn_select6Layout);
        pn_select6Layout.setHorizontalGroup(
            pn_select6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select6Layout.setVerticalGroup(
            pn_select6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengembalian.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Peminjaman");

        javax.swing.GroupLayout pn_btnPeminjamanLayout = new javax.swing.GroupLayout(pn_btnPeminjaman);
        pn_btnPeminjaman.setLayout(pn_btnPeminjamanLayout);
        pn_btnPeminjamanLayout.setHorizontalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPeminjamanLayout.createSequentialGroup()
                .addComponent(pn_select6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnPeminjamanLayout.setVerticalGroup(
            pn_btnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnLaporan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnLaporanMouseMoved(evt);
            }
        });
        pn_btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnLaporanMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnLaporanMouseExited(evt);
            }
        });

        pn_select8.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select8Layout = new javax.swing.GroupLayout(pn_select8);
        pn_select8.setLayout(pn_select8Layout);
        pn_select8Layout.setHorizontalGroup(
            pn_select8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select8Layout.setVerticalGroup(
            pn_select8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Laporan");

        javax.swing.GroupLayout pn_btnLaporanLayout = new javax.swing.GroupLayout(pn_btnLaporan);
        pn_btnLaporan.setLayout(pn_btnLaporanLayout);
        pn_btnLaporanLayout.setHorizontalGroup(
            pn_btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnLaporanLayout.createSequentialGroup()
                .addComponent(pn_select8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnLaporanLayout.setVerticalGroup(
            pn_btnLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnSkripsi.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnSkripsi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnSkripsiMouseMoved(evt);
            }
        });
        pn_btnSkripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnSkripsiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnSkripsiMouseExited(evt);
            }
        });

        pn_select9.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select9Layout = new javax.swing.GroupLayout(pn_select9);
        pn_select9.setLayout(pn_select9Layout);
        pn_select9Layout.setHorizontalGroup(
            pn_select9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select9Layout.setVerticalGroup(
            pn_select9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skripsi1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Skripsi");

        javax.swing.GroupLayout pn_btnSkripsiLayout = new javax.swing.GroupLayout(pn_btnSkripsi);
        pn_btnSkripsi.setLayout(pn_btnSkripsiLayout);
        pn_btnSkripsiLayout.setHorizontalGroup(
            pn_btnSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnSkripsiLayout.createSequentialGroup()
                .addComponent(pn_select9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnSkripsiLayout.setVerticalGroup(
            pn_btnSkripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_btnPetugas.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnPetugas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pn_btnPetugasMouseMoved(evt);
            }
        });
        pn_btnPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPetugasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPetugasMouseExited(evt);
            }
        });

        pn_select10.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_select10Layout = new javax.swing.GroupLayout(pn_select10);
        pn_select10.setLayout(pn_select10Layout);
        pn_select10Layout.setHorizontalGroup(
            pn_select10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_select10Layout.setVerticalGroup(
            pn_select10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/petugas.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Petugas");

        javax.swing.GroupLayout pn_btnPetugasLayout = new javax.swing.GroupLayout(pn_btnPetugas);
        pn_btnPetugas.setLayout(pn_btnPetugasLayout);
        pn_btnPetugasLayout.setHorizontalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPetugasLayout.createSequentialGroup()
                .addComponent(pn_select10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_btnPetugasLayout.setVerticalGroup(
            pn_btnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_menuBarLayout = new javax.swing.GroupLayout(pn_menuBar);
        pn_menuBar.setLayout(pn_menuBarLayout);
        pn_menuBarLayout.setHorizontalGroup(
            pn_menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_btnSkripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnDasbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_menuBarLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lb_logo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_menuBarLayout.setVerticalGroup(
            pn_menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_btnDasbor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_btnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        getContentPane().add(pn_menuBar, java.awt.BorderLayout.LINE_START);

        pn_heder.setCEnd(new java.awt.Color(150, 50, 124));
        pn_heder.setCStart(new java.awt.Color(68, 50, 124));

        btn_s.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setting.png"))); // NOI18N
        btn_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_hederLayout = new javax.swing.GroupLayout(pn_heder);
        pn_heder.setLayout(pn_hederLayout);
        pn_hederLayout.setHorizontalGroup(
            pn_hederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hederLayout.createSequentialGroup()
                .addContainerGap(799, Short.MAX_VALUE)
                .addComponent(btn_s)
                .addContainerGap())
        );
        pn_hederLayout.setVerticalGroup(
            pn_hederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hederLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_s, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        book1.setBackground(new java.awt.Color(255, 255, 255));
        book1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasborLayout = new javax.swing.GroupLayout(pn_dasbor);
        pn_dasbor.setLayout(pn_dasborLayout);
        pn_dasborLayout.setHorizontalGroup(
            pn_dasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_heder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_dasborLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(book1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_dasborLayout.setVerticalGroup(
            pn_dasborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasborLayout.createSequentialGroup()
                .addComponent(pn_heder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pn_dasbor, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pn_btnDasborMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDasborMouseMoved
        if (aktif) {
            pn_btnDasbor.setBackground(new Color(204, 204, 204));
            pn_select1.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnDasborMouseMoved

    private void pn_btnDasborMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDasborMouseExited
        if (aktif) {
            pn_btnDasbor.setBackground(Color.white);
            pn_select1.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnDasborMouseExited

    private void pn_btnAnggotaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseMoved
        if (aktif) {
            pn_btnAnggota.setBackground(new Color(204, 204, 204));
            pn_select2.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnAnggotaMouseMoved

    private void pn_btnAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseExited
        if (aktif) {
            pn_btnAnggota.setBackground(Color.white);
            pn_select2.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnAnggotaMouseExited

    private void pn_btnBukuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseMoved
        if (aktif) {
            pn_btnBuku.setBackground(new Color(204, 204, 204));
            pn_select5.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnBukuMouseMoved

    private void pn_btnBukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseExited
        if (aktif) {
            pn_btnBuku.setBackground(Color.white);
            pn_select5.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnBukuMouseExited

    private void pn_btnPeminjamanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseMoved
        if (aktif) {
            pn_btnPeminjaman.setBackground(new Color(204, 204, 204));
            pn_select6.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnPeminjamanMouseMoved

    private void pn_btnPeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseExited
        if (aktif) {
            pn_btnPeminjaman.setBackground(Color.white);
            pn_select6.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnPeminjamanMouseExited

    private void pn_btnLaporanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnLaporanMouseMoved
        if (aktif) {
            pn_btnLaporan.setBackground(new Color(204, 204, 204));
            pn_select8.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnLaporanMouseMoved

    private void pn_btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnLaporanMouseExited
        if (aktif) {
            pn_btnLaporan.setBackground(Color.white);
            pn_select8.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnLaporanMouseExited

    private void pn_btnDasborMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDasborMouseClicked
        if (aktif) {
            tekan(jLabel2);
            book1.removeAll();
            book1.add(new MenuDasbor(book1, jLabel4, jLabel6, jLabel14, jLabel8, jLabel2));
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnDasborMouseClicked

    private void pn_btnAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnAnggotaMouseClicked
        if (aktif) {
            tekan(jLabel4);
            book1.removeAll();
            book1.add(new MenuAnggota());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnAnggotaMouseClicked

    private void pn_btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnBukuMouseClicked
        if (aktif) {
            tekan(jLabel6);
            book1.removeAll();
            book1.add(new MenuBuku());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnBukuMouseClicked

    private void pn_btnPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPeminjamanMouseClicked
        if (aktif) {
            tekan(jLabel8);
            book1.removeAll();
            book1.add(new MenuPeminjaman());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnPeminjamanMouseClicked

    private void pn_btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnLaporanMouseClicked
        if (aktif) {
            tekan(jLabel12);
            book1.removeAll();
            book1.add(new MenuLaporan());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnLaporanMouseClicked

    private void pn_btnSkripsiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnSkripsiMouseMoved
        if (aktif) {
            pn_btnSkripsi.setBackground(new Color(204, 204, 204));
            pn_select9.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnSkripsiMouseMoved

    private void pn_btnSkripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnSkripsiMouseClicked
        if (aktif) {
            tekan(jLabel14);
            book1.removeAll();
            book1.add(new MenuSkripsi());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnSkripsiMouseClicked

    private void pn_btnSkripsiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnSkripsiMouseExited
        if (aktif) {
            pn_btnSkripsi.setBackground(Color.white);
            pn_select9.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnSkripsiMouseExited

    private void btn_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sMouseClicked
        if (aktif)
            popupMenu.show(btn_s, btn_s.getWidth() - menu.getWidth(), btn_s.getHeight());
    }//GEN-LAST:event_btn_sMouseClicked

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        tekan(null);
        book1.removeAll();
        book1.add(new Profil(mod));
        book1.repaint();
        book1.revalidate();
        popupMenu.setVisible(false);
    }//GEN-LAST:event_menu1MouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        FormLogin log = new FormLogin();
        log.setVisible(true);
        log.revalidate();
        dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void pn_btnPetugasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPetugasMouseMoved
        if (aktif) {
            pn_btnPetugas.setBackground(new Color(204, 204, 204));
            pn_select10.setVisible(true);
        }
    }//GEN-LAST:event_pn_btnPetugasMouseMoved

    private void pn_btnPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPetugasMouseClicked
        if (aktif) {
            tekan(jLabel16);
            book1.removeAll();
            book1.add(new MenuPetugas());
            book1.repaint();
            book1.revalidate();
        }
    }//GEN-LAST:event_pn_btnPetugasMouseClicked

    private void pn_btnPetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPetugasMouseExited
        if (aktif) {
            pn_btnPetugas.setBackground(Color.white);
            pn_select10.setVisible(false);
        }
    }//GEN-LAST:event_pn_btnPetugasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel book1;
    private javax.swing.JLabel btn_s;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menu1;
    private javax.swing.JPanel pn_btnAnggota;
    private javax.swing.JPanel pn_btnBuku;
    private javax.swing.JPanel pn_btnDasbor;
    private javax.swing.JPanel pn_btnLaporan;
    private javax.swing.JPanel pn_btnPeminjaman;
    private javax.swing.JPanel pn_btnPetugas;
    private javax.swing.JPanel pn_btnSkripsi;
    private javax.swing.JPanel pn_dasbor;
    private custom.JPanelGradientHorizontal pn_heder;
    private javax.swing.JPanel pn_menuBar;
    private javax.swing.JPanel pn_select1;
    private javax.swing.JPanel pn_select10;
    private javax.swing.JPanel pn_select2;
    private javax.swing.JPanel pn_select5;
    private javax.swing.JPanel pn_select6;
    private javax.swing.JPanel pn_select8;
    private javax.swing.JPanel pn_select9;
    // End of variables declaration//GEN-END:variables

    private void tekan(JLabel lb) {
        jLabel2.setFont(new Font("Segoe UI", 0, 14));
        jLabel4.setFont(new Font("Segoe UI", 0, 14));
        jLabel6.setFont(new Font("Segoe UI", 0, 14));
        jLabel8.setFont(new Font("Segoe UI", 0, 14));
        jLabel12.setFont(new Font("Segoe UI", 0, 14));
        jLabel14.setFont(new Font("Segoe UI", 0, 14));
        jLabel16.setFont(new Font("Segoe UI", 0, 14));

        if (lb != null) {
            lb.setFont(new Font("Segoe UI", 1, 14));
        }
    }
}
