/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DaoEmail;
import dao.DaoLaporan;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JasperPrint;
import servis.ServiceEmail;
import servis.ServiceLaporan;

/**
 *
 * @author fatiq
 */
public class MenuLaporan extends javax.swing.JPanel {

    /**
     * Creates new form Dasbor
     */
    private ServiceLaporan servis = new DaoLaporan();
    private ServiceEmail sevEmail = new DaoEmail();
    private JasperPrint print = null;

    public MenuLaporan() {
        initComponents();
        resetPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_conten = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pn_print = new javax.swing.JPanel();
        jPanelGradientVertikal1 = new custom.JPanelGradientVertikal();
        jPanel1 = new javax.swing.JPanel();
        cbx_pilih = new javax.swing.JComboBox<>();
        btn_cetak = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        pn_email = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        pn_cari = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbx_cari = new javax.swing.JComboBox<>();
        tf_cari = new javax.swing.JTextField();

        pn_conten.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        jLabel1.setText("Laporana Perpustakaan");

        jSeparator1.setBackground(new java.awt.Color(68, 50, 124));
        jSeparator1.setForeground(new java.awt.Color(68, 50, 124));

        pn_print.setBackground(new java.awt.Color(255, 255, 255));
        pn_print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 50, 124)));

        javax.swing.GroupLayout pn_printLayout = new javax.swing.GroupLayout(pn_print);
        pn_print.setLayout(pn_printLayout);
        pn_printLayout.setHorizontalGroup(
            pn_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pn_printLayout.setVerticalGroup(
            pn_printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelGradientVertikal1.setCEnd(new java.awt.Color(150, 50, 124));
        jPanelGradientVertikal1.setCStart(new java.awt.Color(68, 50, 124));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbx_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Jenis Laporan--", "Laporan Anggota", "Laporan Buku", "Laporan Skripsi", "Laporan Peminjaman" }));
        cbx_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pilihActionPerformed(evt);
            }
        });

        btn_cetak.setBackground(new java.awt.Color(0, 200, 0));
        btn_cetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cetak.setForeground(new java.awt.Color(0, 200, 0));
        btn_cetak.setText("LOAD");
        btn_cetak.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_cetakMouseMoved(evt);
            }
        });
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cetakMouseExited(evt);
            }
        });
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(180, 160, 59));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(180, 160, 59));
        btn_batal.setText("RESET");
        btn_batal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_batalMouseMoved(evt);
            }
        });
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_batalMouseExited(evt);
            }
        });
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        pn_email.setBackground(new java.awt.Color(255, 255, 255));
        pn_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 50, 124)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 50, 124));
        jLabel2.setText("Kirim Laporan ke :");

        tf_email.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_email.setForeground(new java.awt.Color(68, 50, 124));
        tf_email.setText("email");
        tf_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        tf_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_emailFocusLost(evt);
            }
        });

        btn_tambah.setBackground(new java.awt.Color(68, 50, 124));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(68, 50, 124));
        btn_tambah.setText("KIRIM");
        btn_tambah.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btn_tambahMouseMoved(evt);
            }
        });
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tambahMouseExited(evt);
            }
        });
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_emailLayout = new javax.swing.GroupLayout(pn_email);
        pn_email.setLayout(pn_emailLayout);
        pn_emailLayout.setHorizontalGroup(
            pn_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_email)
                    .addGroup(pn_emailLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_emailLayout.setVerticalGroup(
            pn_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_cari.setBackground(new java.awt.Color(255, 255, 255));
        pn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 50, 124)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 50, 124));
        jLabel3.setText("Laporan Berdasarkan ");

        cbx_cari.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbx_cari.setForeground(new java.awt.Color(204, 204, 204));
        cbx_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "ISBN", "JUDUL", "KATEGORI", "PENGARANG" }));
        cbx_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tf_cari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tf_cari.setForeground(new java.awt.Color(68, 50, 124));
        tf_cari.setText("Cari");
        tf_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        tf_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_cariFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pn_cariLayout = new javax.swing.GroupLayout(pn_cari);
        pn_cari.setLayout(pn_cariLayout);
        pn_cariLayout.setHorizontalGroup(
            pn_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cari)
                    .addGroup(pn_cariLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbx_cari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_cariLayout.setVerticalGroup(
            pn_cariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbx_pilih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_cari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbx_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cetak)
                .addGap(18, 18, 18)
                .addComponent(pn_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btn_batal)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelGradientVertikal1Layout = new javax.swing.GroupLayout(jPanelGradientVertikal1);
        jPanelGradientVertikal1.setLayout(jPanelGradientVertikal1Layout);
        jPanelGradientVertikal1Layout.setHorizontalGroup(
            jPanelGradientVertikal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradientVertikal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGradientVertikal1Layout.setVerticalGroup(
            jPanelGradientVertikal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGradientVertikal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_contenLayout = new javax.swing.GroupLayout(pn_conten);
        pn_conten.setLayout(pn_contenLayout);
        pn_contenLayout.setHorizontalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pn_contenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_contenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 554, Short.MAX_VALUE))
                    .addGroup(pn_contenLayout.createSequentialGroup()
                        .addComponent(jPanelGradientVertikal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_contenLayout.setVerticalGroup(
            pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_contenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGradientVertikal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cetakMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseMoved
        btn_cetak.setForeground(Color.white);
    }//GEN-LAST:event_btn_cetakMouseMoved

    private void btn_cetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseExited
        btn_cetak.setForeground(new Color(0, 200, 0));
    }//GEN-LAST:event_btn_cetakMouseExited

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        String cr = tf_cari.getText();
        if (cr.equals("Cari")) {
            switch (cbx_pilih.getSelectedIndex()) {
                case 0:
                    resetPanel();
                    break;
                case 1:
                    print = servis.cetakAnggota(pn_print);
                    pn_email.setVisible(true);
                    break;
                case 2:
                    print = servis.cetakBuku(pn_print);
                    pn_email.setVisible(true);
                    break;
                case 3:
                    print = servis.cetakSkripsi(pn_print);
                    pn_email.setVisible(true);
                    break;
                case 4:
                    switch (cbx_cari.getSelectedIndex()) {
                        case 0:
                            print = servis.laporanPeminjamanPerbulanPinjam(pn_print);
                            break;
                        case 1:
                            print = servis.laporanPeminjamanPerbulanKembali(pn_print);
                            break;
                        case 2:
                            print = servis.laporanPeminjamanTerbanyak(pn_print);
                            break;
                        case 3:
                            print = servis.laporanPeminjamanPerAngkatan(pn_print);
                            break;
                        case 4:
                            print = servis.laporanPeminjamanKategoriTerbanyak(pn_print);
                            break;
                    }
                    pn_email.setVisible(true);
                    break;
            }
        } else {
            String k = cbx_cari.getSelectedItem().toString();
            switch (cbx_pilih.getSelectedIndex()) {
                case 0:
                    resetPanel();
                    break;
                case 1:
                    print = servis.cetakAnggotaCari(pn_print, cr, k);
                    pn_email.setVisible(true);
                    break;
                case 2:
                    print = servis.cetakBukuCari(pn_print, cr, k);
                    pn_email.setVisible(true);
                    break;
                case 3:
                    print = servis.cetakSkripsiCari(pn_print, cr, k);
                    pn_email.setVisible(true);
                    break;
            }
        }
        jLabel1.requestFocus();
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void btn_batalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseMoved
        btn_batal.setForeground(Color.white);
    }//GEN-LAST:event_btn_batalMouseMoved

    private void btn_batalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseExited
        btn_batal.setForeground(new Color(180, 160, 59));
    }//GEN-LAST:event_btn_batalMouseExited

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        resetPanel();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tf_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_emailFocusGained
        if (tf_email.getText().equalsIgnoreCase("email"))
            tf_email.setText("");
    }//GEN-LAST:event_tf_emailFocusGained

    private void tf_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_emailFocusLost
        if (tf_email.getText().equalsIgnoreCase("email") || tf_email.getText().equalsIgnoreCase(""))
            tf_email.setText("email");
    }//GEN-LAST:event_tf_emailFocusLost

    private void tf_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cariFocusGained
        if (tf_cari.getText().equalsIgnoreCase("Cari"))
            tf_cari.setText("");
    }//GEN-LAST:event_tf_cariFocusGained

    private void tf_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cariFocusLost
        if (tf_cari.getText().equalsIgnoreCase(""))
            tf_cari.setText("Cari");
    }//GEN-LAST:event_tf_cariFocusLost

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = tf_email.getText();
        String y = "";
        switch (cbx_pilih.getSelectedIndex()) {
            case 1:
                y = "Laporan Data Anggota";
                break;
            case 2:
                y = "Laporan Data Buku";
                break;
            case 3:
                y = "Laporan Data Skripsi";
                break;
        }
        sevEmail.kririm(x, y, y, print);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_tambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseExited
        btn_tambah.setForeground(new Color(68, 50, 124));
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/tambah1.png"));
        //        btn_tambah.setIcon(icon);
        jLabel1.requestFocus();
    }//GEN-LAST:event_btn_tambahMouseExited

    private void btn_tambahMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseMoved
        btn_tambah.setForeground(Color.white);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/tambah.png"));
        //        btn_tambah.setIcon(icon);
    }//GEN-LAST:event_btn_tambahMouseMoved

    private void cbx_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pilihActionPerformed
        pn_cari.setVisible(true);
        tf_cari.setVisible(true);
        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("ID");
        switch (cbx_pilih.getSelectedIndex()) {
            case 1:
                cb.addElement("NAMA");
                cb.addElement("NIM");
                cb.addElement("ALAMAT");
                cb.addElement("PROGRAM STUDI");
                cb.addElement("FAKULTAS");
                cb.addElement("ANGKATAN");
                cbx_cari.setModel(cb);
                break;
            case 2:
                cb.addElement("ISBN");
                cb.addElement("JUDUL");
                cb.addElement("KATEGORI");
                cb.addElement("PENGARANG");
                cbx_cari.setModel(cb);
                break;
            case 3:
                cb.addElement("JUDUL");
                cb.addElement("KATEGORI");
                cb.addElement("PEMBIMBING");
                cb.addElement("PENULIS");
                cb.addElement("PROGRAM STUDI");
                cb.addElement("FAKULTAS");
                cbx_cari.setModel(cb);
                break;
            case 4:
                setPeminjaman();
                break;
        }
    }//GEN-LAST:event_cbx_pilihActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cbx_cari;
    private javax.swing.JComboBox<String> cbx_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private custom.JPanelGradientVertikal jPanelGradientVertikal1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pn_cari;
    private javax.swing.JPanel pn_conten;
    private javax.swing.JPanel pn_email;
    private javax.swing.JPanel pn_print;
    private javax.swing.JTextField tf_cari;
    private javax.swing.JTextField tf_email;
    // End of variables declaration//GEN-END:variables

    private void resetPanel() {
        pn_print.removeAll();
        pn_print.repaint();
        pn_print.revalidate();
        cbx_pilih.setSelectedIndex(0);
        tf_cari.setText("Cari");
        pn_email.setVisible(false);
        pn_cari.setVisible(false);
        print = null;
    }

    private void setPeminjaman() {
        tf_cari.setVisible(false);
        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        cb.addElement("Perbulan Pinjam");
        cb.addElement("Perbulan Kembali");
        cb.addElement("Terbanyak");
        cb.addElement("Perangkatan");
        cb.addElement("Kategori Terbanyak");
        cbx_cari.setModel(cb);
    }

}
