/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DaoPetugas;
import dao.Encrypt;
import java.awt.Color;
import javax.swing.JOptionPane;
import parsisten.Petugas;
import servis.ServicePetugas;

/**
 *
 * @author fatiq
 */
public class TambahPetugas extends javax.swing.JDialog {

    /**
     * Creates new form TambahBuku
     */
    private Petugas mod = new Petugas();
    private ServicePetugas servis = new DaoPetugas();

    public TambahPetugas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel1.requestFocus();
        tf_id.setText(servis.nomer());
        unhide1.setVisible(false);
        unhide2.setVisible(false);
    }

    public TambahPetugas(java.awt.Frame parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        jLabel1.requestFocus();
        mod = servis.getById(id);

        setForm(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGradientVertikal1 = new custom.JPanelGradientVertikal();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        unhide1 = new javax.swing.JLabel();
        hide1 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_tlp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_pass = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        tf_pass1 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        cbx_jk = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        unhide2 = new javax.swing.JLabel();
        hide2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LibraLinx Tambah Buku");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/iconlibralinx.png")).getImage());

        jPanelGradientVertikal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 50, 124)));
        jPanelGradientVertikal1.setCStart(new java.awt.Color(68, 50, 124));
        jPanelGradientVertikal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Petugas");
        jPanelGradientVertikal1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unhide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unhide.png"))); // NOI18N
        unhide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unhide1MouseClicked(evt);
            }
        });
        jPanel2.add(unhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        hide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide1MouseClicked(evt);
            }
        });
        jPanel2.add(hide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 30, 20));

        tf_id.setEditable(false);
        tf_id.setForeground(new java.awt.Color(68, 50, 124));
        tf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 208, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 50, 124));
        jLabel2.setText("ID Petugas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 50, 124));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 6, -1, -1));

        tf_nama.setForeground(new java.awt.Color(68, 50, 124));
        tf_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 37, 583, 30));

        tf_tlp.setForeground(new java.awt.Color(68, 50, 124));
        tf_tlp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        tf_tlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_tlpKeyTyped(evt);
            }
        });
        jPanel1.add(tf_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 208, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 50, 124));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        tf_email.setForeground(new java.awt.Color(68, 50, 124));
        tf_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 203, 30));

        tf_alamat.setForeground(new java.awt.Color(68, 50, 124));
        tf_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 368, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 50, 124));
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        btn_simpan.setBackground(new java.awt.Color(0, 200, 0));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 325, -1, -1));

        btn_batal.setBackground(new java.awt.Color(200, 0, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 325, 117, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 50, 124));
        jLabel9.setText("Telephone");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 50, 124));
        jLabel10.setText("Username");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        tf_username.setForeground(new java.awt.Color(68, 50, 124));
        tf_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 208, 30));

        tf_pass.setForeground(new java.awt.Color(68, 50, 124));
        tf_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        jPanel1.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 208, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 50, 124));
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        tf_pass1.setForeground(new java.awt.Color(68, 50, 124));
        tf_pass1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(68, 50, 124)));
        tf_pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tf_pass1MouseExited(evt);
            }
        });
        tf_pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pass1KeyTyped(evt);
            }
        });
        jPanel1.add(tf_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 203, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 50, 124));
        jLabel12.setText("Ulangi Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        cbx_jk.setForeground(new java.awt.Color(68, 50, 124));
        cbx_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Jenis Kelamin-", "L", "P" }));
        cbx_jk.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(68, 50, 124)));
        jPanel1.add(cbx_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 368, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 50, 124));
        jLabel6.setText("Jenis Kelamin");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        cbx_level.setForeground(new java.awt.Color(68, 50, 124));
        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Jenis Level-", "Admin", "Staff" }));
        cbx_level.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(68, 50, 124)));
        jPanel1.add(cbx_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 203, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 50, 124));
        jLabel13.setText("Level");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 209, 15));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        unhide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unhide.png"))); // NOI18N
        unhide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unhide2MouseClicked(evt);
            }
        });
        jPanel3.add(unhide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        hide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hide.png"))); // NOI18N
        hide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hide2MouseClicked(evt);
            }
        });
        jPanel3.add(hide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jPanelGradientVertikal1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 815, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradientVertikal1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGradientVertikal1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if (valid()) {
            mod.setIdPetugas(tf_id.getText());
            mod.setNama(tf_nama.getText());
            mod.setTelephone(tf_tlp.getText());
            mod.setEmail(tf_email.getText());
            mod.setAlamat(tf_alamat.getText());
            mod.setUsername(tf_username.getText());
            mod.setLevel(cbx_level.getSelectedItem().toString());
            char[] ray = cbx_jk.getSelectedItem().toString().toCharArray();
            mod.setJenisKelamin(ray[0]);

            if (jLabel1.getText().equalsIgnoreCase("Tambah Petugas")) {
                mod.setPassword(Encrypt.getmd5java(tf_pass.getText()));
                servis.tambahData(mod);
            } else {
                servis.ubahData(mod);
            }
            dispose();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tf_tlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_tlpKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a))
            evt.consume();
    }//GEN-LAST:event_tf_tlpKeyTyped

    private void tf_pass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pass1KeyTyped
        String pass = tf_pass.getText();
        String pass1 = tf_pass1.getText();
        if (pass.equals("")) {
            jLabel4.setText("Passsord tidak boleh kosong");
            jLabel4.setForeground(new Color(200, 0, 0));
        } else if (pass.equals(pass1)) {
            jLabel4.setText("Passsord sama");
            jLabel4.setForeground(new Color(0, 200, 0));
        } else {
            jLabel4.setText("Passsord tidak sama");
            jLabel4.setForeground(new Color(200, 0, 0));
        }
    }//GEN-LAST:event_tf_pass1KeyTyped

    private void tf_pass1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_pass1MouseExited
        String pass = tf_pass.getText();
        String pass1 = tf_pass1.getText();
        if (pass.equals("")) {
            jLabel4.setText("Passsord tidak boleh kosong");
            jLabel4.setForeground(new Color(200, 0, 0));
        } else if (pass.equals(pass1)) {
            jLabel4.setText("Passsord sama");
            jLabel4.setForeground(new Color(0, 200, 0));
        } else {
            jLabel4.setText("Passsord tidak sama");
            jLabel4.setForeground(new Color(200, 0, 0));
        }
    }//GEN-LAST:event_tf_pass1MouseExited

    private void hide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide1MouseClicked
        tf_pass.setEchoChar((char) 0);
        hide1.setVisible(false);
        unhide1.setVisible(true);
    }//GEN-LAST:event_hide1MouseClicked

    private void unhide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhide1MouseClicked
        tf_pass.setEchoChar('*');
        hide1.setVisible(true);
        unhide1.setVisible(false);
    }//GEN-LAST:event_unhide1MouseClicked

    private void unhide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unhide2MouseClicked
        tf_pass1.setEchoChar('*');
        hide2.setVisible(true);
        unhide2.setVisible(false);
    }//GEN-LAST:event_unhide2MouseClicked

    private void hide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hide2MouseClicked
        tf_pass1.setEchoChar((char) 0);
        hide2.setVisible(false);
        unhide2.setVisible(true);
    }//GEN-LAST:event_hide2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TambahPetugas dialog = null;
                dialog = new TambahPetugas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cbx_jk;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JLabel hide1;
    private javax.swing.JLabel hide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private custom.JPanelGradientVertikal jPanelGradientVertikal1;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JPasswordField tf_pass1;
    private javax.swing.JTextField tf_tlp;
    private javax.swing.JTextField tf_username;
    private javax.swing.JLabel unhide1;
    private javax.swing.JLabel unhide2;
    // End of variables declaration//GEN-END:variables

    private void setForm(Petugas mod) {
        jLabel1.setText("Perbarui Data Petugas");

        tf_id.setText(mod.getIdPetugas());
        tf_nama.setText(mod.getNama());
        tf_tlp.setText(mod.getTelephone());
        tf_email.setText(mod.getEmail());
        tf_alamat.setText(mod.getAlamat());
        cbx_level.setSelectedItem(mod.getLevel());
        cbx_jk.setSelectedItem(mod.getJenisKelamin().toString());
        tf_username.setText(mod.getUsername());

        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        tf_pass.setVisible(false);
        tf_pass1.setVisible(false);

        tf_id.setEditable(false);
        tf_nama.setEditable(false);
        tf_tlp.setEditable(false);
        tf_email.setEditable(false);
        tf_alamat.setEditable(false);
        cbx_jk.setEditable(false);
        tf_username.setEditable(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
    }

    private boolean valid() {
        boolean ok = true;
        if(cbx_level.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(null, "Plih level dengan benar");
           ok = false;
        } else if(cbx_jk.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(null, "Plih Jenis kelamin dengan benar");
           ok = false;
        }
        return ok;
    }
}
